[can_request_logs]
label_list={"project": "as","environment":"demo","filename":"/data/logs/request_info.log"}
label_name=starttime traceidwithskywalking traceidwiithaloudata api url selfstatus ip cost responsecode tnid userid selfcode
lokiexclre=
lokire=
recordslimit=100000
regex=(\d+-\d+-\d+\s\S+)\s\[(.*?)\]\s\[(.*?)\]\s\[.*?\]\s\w+\s+(\S+)\s-\s(.*?)\|(.*?)\|(.*?)\|(.*?)\|(.*?)\|(.*?)\|(.*?)\|(.*?)\|.*?
showlabelvaluelists=traceidwiithaloudata
value_label=cost


[can_request_query_metrics_num]
json_keys=Metrics
label_list={"project": "as","environment":"demo","filename":"/data/logs/request_info.log"}
label_name=starttime ip responsecode tnid userid json
lokiexclre=
lokire=/queryMetrics
recordslimit=100000
regex=(\d+-\d+-\d+\s\S+)\s\[.*?\]\s\[.*?\]\s\w+\s+\S+\s-\s.*?\|(.*?)\|.*?\|(.*?)\|(.*?)\|(.*?)\|.*?\|.*?\|(.*)
showlabelvaluelists=
value_label=

[semantic_error_logs]
label_list={"environment":"demo","filename":"/data/logs/semantic_error.log","job":"semantic-demo","project":"as"}
label_name=starttime traceidwithskywalking traceidwiithaloudata errormsg
lokiexclre=
lokire=
recordslimit=100000
regex=(\d+-\d+-\d+\s\S+)\s\[(.*?)\]\s\[(.*?)\]\s\[.*?\]\s\w+\s+(.*)

[jscip_error_logs]
label_list={"environment":"demo","filename":"/data/logs/jscip_info.log","job":"jscip-demo","project":"as"}
label_name=starttime traceidwithskywalking traceidwiithaloudata errormsg
lokiexclre=
lokire=ERROR
recordslimit=100000
regex=(\d+-\d+-\d+\s\S+)\s\[(.*?)\]\s\[(.*?)\]\s\[.*?\]\s\w+\s+(.*)


[anymetrics_error_logs]
label_list={"environment":"demo","filename":"/data/logs/anymetrics_error.log","job":"anymetrics-demo","project":"as"}
label_name=starttime traceidwithskywalking traceidwiithaloudata errormsg
lokiexclre=
lokire=
recordslimit=100000
regex=(\d+-\d+-\d+\s\S+)\s\[(.*?)\]\s\[(.*?)\]\s\[.*?\]\s\w+\s+(.*)


[query_phase_time_logs]
label_list={"environment":"demo","filename":"/data/logs/semantic_monitor.log","job":"semantic-demo","project":"as"}
; label_name=starttime traceidwiithaloudata traceidwithskywalking stages cost
lokiexclre=
lokire=
recordslimit=100000
regex=(\d+-\d+-\d+\s\S+)\|(.*?)\|(.*?)\|(.*?)\|(.*)
value_label=cost

[dingdingwebhook]
listrebots={"air":{"test":{"accessToken":"dd0dfc3e5f598a4c94b6bcfebbfc1d88281898b9658642294d6ff60f11a4f149","secret":"SECf20d8b02a0dee2df7dd02d2ff55498d0f7508fb234e0cadc4e5adace2e74acfe"},"prod":{"accessToken":"","secret":""}},"joinsight":{"test":{"accessToken":"dd0dfc3e5f598a4c94b6bcfebbfc1d88281898b9658642294d6ff60f11a4f149","secret":"SECf20d8b02a0dee2df7dd02d2ff55498d0f7508fb234e0cadc4e5adace2e74acfe"},"prod":{"accessToken":"","secret":""}},"bigmeta":{"test":{"accessToken":"dd0dfc3e5f598a4c94b6bcfebbfc1d88281898b9658642294d6ff60f11a4f149","secret":"SECf20d8b02a0dee2df7dd02d2ff55498d0f7508fb234e0cadc4e5adace2e74acfe"},"prod":{"accessToken":"","secret":""}},"default":{"default":{"accessToken":"8f3a1b5cd395675557bbd7a5fb80c666b66866f49f48a6d165f9ae3fa147ef28","secret":""}}}

[global]
cmbalarminterface=http://10.5.100.4:5003/get?message=
consulipport=127.0.0.1:8500
delayupdateseconds=15
nacosip=10.5.20.26
nacosport=8848
namespaceid=can-release
pageno=1
pagesize=100
pushgatewayipport=10.5.101.3:9091
servicelist=semantic jscip
serviceport=8502



[jscip]
servicelist={"providers:com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:jscip":"1","providers:com.aloudata.jscip.common.service.session.facade.CipSessionRepositoryFacade:1.0.0:":"1","providers:com.aloudata.jscip.common.service.session.facade.SessionFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.CipDataSourceFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.DataAcqTaskFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.DataSourceFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.DataStatisticsFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.HealthmonitorFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.RoleFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.TenantFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.UserFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.UserPropertyDefFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.UserPropertyFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.UserQueryFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.UserSourceConfigFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.UserTenantRelationFacade:1.0.0:":"1","providers:com.aloudata.jscip.facade.WorkspaceFacade:1.0.0:":"1"}

[mixedformat]
collectionscopeseconds=30
cycle=0.5m
label_len=128
latencycollectionseconds=30
requestlogs= can_request_logs 
requestlogslabel_name=starttime traceidwithskywalking traceidwiithaloudata api url selfstatus ip cost responsecode tnid userid selfcode
errorlogs= semantic_error_logs jscip_error_logs anymetrics_error_logs
errorlogslabel_name=starttime traceidwithskywalking traceidwiithaloudata errormsg 
queryphasetimelogs= query_phase_time_logs
queryphasetimelogslabel_name=starttime traceidwiithaloudata traceidwithskywalking stages cost
lokiipport=10.5.20.35:3100

[semantic]
servicelist={"providers:com.aloudata.semantic.common.service.facade.AccelerateFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.AccelerateMtFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.AcceleratePlanFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.AccelerateResultPlanFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.ApiInfoFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.ConfigFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.CustomCalendarFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DataModelDraftFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DataModelFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DatasetFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DatasetStaticsFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DatasetTaskExecService:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DatasourceFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DateTagFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.DimensionFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.ExprFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.LineageFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.ManualTaskFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.MetricFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.MetricPublishServiceFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.QueryCacheFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.ResourcePublishServiceFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.SemanticUserFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.SqlGenerateFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.SystemConfigFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.TableFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.attribution.MetricTreeAnalysisReportFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.openmetric.MetricDataQueryFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.openmetric.QueryViewFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.query.AMQueryFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.queryrecord.QueryRecordFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.scheduler.SchedulerTaskFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.AuthorityQueryServiceFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.AuthorityServiceFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.DatasourceInfoFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.FilterParserFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.MetricDetailServiceFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.MetricServiceFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.RowAuthRuleFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.SqlParserFacade:1.0.0:":"1","providers:com.aloudata.semantic.common.service.facade.service.UserGroupFacade:1.0.0:":"1","providers:com.aloudata.semantic.query.QueryManager:1.0.0:":"1"}
